### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by TsukaJoon** [veethahavya-CU-cz/delft3dfm_dockerized#1]
Hello，I got some trouble follow your code. I am working in Centos. Could you kindly give me your E-mail to contact with you? 

Your sincerely fellow!

**Comment by veethahavya-CU-cz** [comment]
fixed in recent commit ([fdf44af](https://github.com/veethahavya-CU-cz/delft3dfm_dockerized/commit/fdf44afa6b9bda1465b71fcd080ef94da8b90a14))
