### ISSUE TITLE
Problem building the docker

### ISSUE THREAD

**Issue by carmenafa** [veethahavya-CU-cz/delft3dfm_dockerized#3]
Hello,

I have been able to install delft3d and I have the folder included in /opt. However when I run the command "docker build --network=host -t delft3dfm ." I get the following error: "unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /Dockerfile: no such file or directory". It is the first time I use docker so I made sure that it is correctly installed using the test image "docker run hello-world" and it seems that everything is correct. Could you give me some indication to solve this error?

Thank you very much in advance for the help and for uploading this repository. I am learning a lot.

Best regards,
Carmen

**Comment by veethahavya-CU-cz** [comment]
Hi Carmen,

Please follow the readme step-by-step and you should be able to run delft3dfm on the newly built docker container, provided you have set up docker correctly. I can not reproduce your issue, and it may be machine dependent. I recommend you try to build the docker container on a VM.
(note: you do not need to install delft3dfm by yourself before building the docker container)
